#!/bin/sh
cd /home/kevin/apps/pomandhoney
npm install
pm2 stop all
pm2 delete all
pm2 start index.js
echo "*******************************************"
echo "Server has been updated."
echo "*******************************************"
